auth/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('obtain_token', views.obtain_token, name='obtain-token'),
    path('refresh_token', views.refresh_token, name='refresh-token'),
    path('logout', views.logout, name='logout'),

]

films/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('popular', views.popular, name='popular'),
    path('upcoming', views.upcoming, name='upcoming'),
    path('festivals', views.festivals, name='festivals'),
    path('statistics', views.statistics, name='statistics'),
    path('top', views.top, name='top'),
    path('<int:movie_id>/add', views.add_movie, name='add'),
    path('<int:movie_id>/wishlist',
         views.wishlist_movie, name='wishlist-film'),
    path('wishlist', views.wishlist, name='wishlist-index'),
    path('<int:id>/like', views.like, name='like'),
    path('<int:id>/dislike', views.dislike, name='dislike'),
    path('<int:id>/view', views.get_film, name='view'),
    path('chart', views.years_chart, name='years-chart'),
    path('runtime-chart', views.runtime_chart, name='runtime-chart'),
    path('decades-chart', views.decades_chart, name='decades-chart'),
    path('ratings-chart', views.ratings_chart, name='ratings-chart'),
    path('genres', views.genres, name='genres'),
    path('discover', views.discover, name='discover'),


]

filmtracker/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
from django.contrib.auth.views import LoginView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from django.contrib.auth import authenticate, login

urlpatterns = [
    path('', include('homepage.urls')),
    path('films/', include(('films.urls', 'films'), namespace='films')),
    path('people/', include(('people.urls', 'people'), namespace='people')),
    path('shows/', include(('shows.urls', 'shows'), namespace='shows')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include(('auth.urls', 'auth'), namespace='auth')),

]

shows/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/view', views.get_show, name='view'),
    path('popular', views.popular, name='popular'),
    path('<int:show_id>/add', views.add_show, name='add'),
    path('<int:id>/season/<int:season_number>',
         views.get_season, name='season'),
    path('<int:id>/season/<int:season_number>/episode/<int:episode_number>',
         views.get_episode, name='episode'),
    path('search', views.search, name='search'),
    path('<int:show_id>/wishlist',
         views.wishlist_show, name='wishlist-show'),
    path('wishlist', views.wishlist, name='wishlist-index'),
    path('statistics', views.statistics, name='statistics')
]

shows/models.py
from django.db import models

# Create your models here.


class Show(models.Model):
    name = models.CharField(max_length=200)
    original_language = models.CharField(max_length=200)
    original_name = models.CharField(max_length=200)
    type_of_show = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    overview = models.TextField(null=True)
    movie_db_id = models.IntegerField(null=True)
    comments = models.CharField(max_length=200, null=True)
    popularity = models.FloatField(null=True)
    number_of_seasons = models.IntegerField(null=True)
    number_of_episodes = models.IntegerField(null=True)
    runtime = models.IntegerField(null=True)
    first_air_date = models.DateField(null=True)
    vote_average = models.FloatField(null=True)
    date_watched = models.DateField(null=True)
    added = models.BooleanField(null=True)
    wishlisted = models.BooleanField(null=True)
    score = models.FloatField(null=True)

    def __str__(self):
        return self.name


class Season(models.Model):
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    season_number = models.IntegerField()
    overview = models.CharField(max_length=200, null=True)
    movie_db_id = models.IntegerField()
    number_of_episodes = models.IntegerField()

    def __str__(self):
        return '%s season %s' % (self.show.name, self.season_number)


class Episode(models.Model):
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    season_number = models.IntegerField()
    overview = models.CharField(max_length=200, null=True)
    movie_db_id = models.IntegerField()
    episode_number = models.IntegerField()

    def __str__(self):
        return '%s episode %s' % (self.season.name, self.episode_number)


class Genre(models.Model):
    name = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    show = models.ForeignKey(Show, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Recommendation(models.Model):
    name = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    show = models.ForeignKey(Show, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CrewCredit(models.Model):
    name = models.CharField(max_length=200)
    known_for = models.CharField(
        max_length=200, null=True, default='Production')
    job = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    credit_id = models.CharField(max_length=200, null=True)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)

    def __str__(self):
        return '%s as %s in %s' % (self.name, self.job, self.show)


class ActingCredit(models.Model):
    name = models.CharField(max_length=200)
    character = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    credit_id = models.CharField(max_length=200, null=True)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)

    def __str__(self):
        return '%s as %s in %s' % (self.name, self.character, self.show)

shows/forms.py
from django import forms
from django.forms import ModelForm
from .models import Show


class ShowSearchForm(forms.Form):
    search_query = forms.CharField(label='Show Title', max_length=100)


class ShowForm(ModelForm):
    class Meta:
        model = Show
        fields = ['score', 'comments', 'date_watched']  # , 'date_watched'
        # Thanks to https: // stackoverflow.com/questions/49440853/django-2-0-modelform-datefield-not-displaying-as-a-widget
        widgets = {
            'date_watched': forms.DateInput(format=('%m/%d/%Y'), attrs={'class': 'form-control', 'placeholder': 'Select a date', 'type': 'date'}),
        }

shows/views.py
from django.shortcuts import render
from django.urls import reverse

from . import tv_helper
from .models import Show, ActingCredit, Genre, CrewCredit
import requests
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ShowSearchForm, ShowForm
import os
from django.db.models import Avg, Max, Q, Count, FloatField, F
from . import stats
movie_api_key = os.getenv("MOVIE_DB_KEY")
# Create your views here.


def index(request):
    # pylint: disable=no-member
    context = {'shows': Show.objects.filter(added=True)}
    return render(request, 'shows/index.html', context)


def search_results(request):
    return render(request, 'tv/search.html', {})


def add_show(request, show_id):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ShowForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            score = form.cleaned_data['score']
            comments = form.cleaned_data['comments']
            date_watched = form.cleaned_data['date_watched']

            show = tv_helper.get_show_for_create(show_id)
            added_show = Show(name=show['name'],
                              original_language=show['original_language'],
                              original_name=show['original_name'],
                              overview=show['overview'],
                              popularity=show['popularity'],
                              first_air_date=show['first_air_date'],
                              vote_average=show['vote_average'],
                              added=show['added'],
                              type_of_show=show['type_of_show'],
                              status=show['status'],
                              number_of_episodes=show['number_of_episodes'],
                              number_of_seasons=show['number_of_seasons'],
                              score=score,
                              comments=comments,
                              date_watched=date_watched,
                              movie_db_id=show['movie_db_id']
                              )
            added_show.save()
            return HttpResponseRedirect(reverse('shows:view', args=(show['movie_db_id'],)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ShowForm()

    return render(request, 'shows/add.html', {'form': form, 'id': show_id})


def get_season(request, id, season_number):
    season = tv_helper.get_season(id, season_number)
    show = tv_helper.get_show_details(id)
    return render(request, f'shows/season.html', {'show': show, 'season': season})


def get_episode(request, id, season_number, episode_number):
    season = tv_helper.get_season(id, season_number)
    show = tv_helper.get_show_details(id)
    episode = tv_helper.get_episode(id, season_number, episode_number)
    return render(request, f'shows/episode.html', {'show': show, 'season': season, 'episode': episode})


def get_show(request, id):
    cast, crew = tv_helper.get_cast_and_crew(id)
    show = tv_helper.get_show_details(id)
    recommendations = tv_helper.get_recommendations(id)
    where = tv_helper.get_where_to_watch(id)
    # pylint: disable=no-member
    wishlisted = Show.objects.filter(
        wishlisted=True, movie_db_id=show['id']).exists()
    watched = Show.objects.filter(
        added=True, movie_db_id=show['id']).exists()
    show['recommendations'] = recommendations
    poster = tv_helper.get_poster(show)
    return render(request, f'shows/show.html', {'show': show, 'cast': cast, 'crew': crew, 'wishlisted': wishlisted, 'watched': watched, 'poster': poster, 'where': where})


def statistics(request):
    # pylint: disable=no-member
    shows = Show.objects.filter(wishlisted=True)
    genres = stats.get_genre_percentages()
    runtime_breakdowns = stats.get_runtime_breakdowns()
    cast = ActingCredit.objects.order_by().values(
        'name', 'movie_db_id').annotate(count=Count('id')).order_by('-count')
    average_rating = stats.get_average_rating()
    most_recommended = stats.get_most_recommended()
    nb_credits = stats.get_nb_credit_percentages()
    cast = stats.get_actor_percentages()
    decade_breakdown = stats.get_decade_percentages()
    year_percentages = stats.get_year_percentages()
    headline = stats.get_headline()
    statistics = {
        'average_length': Show.aggregate(Avg('runtime')),
        'average_rating': average_rating,
        'genres': genres,
        'credits': credits,
        'cast': cast,
        'num_shows': len(Show.objects.all()),
        'nb_credits': nb_credits,
        'runtime_breakdown': runtime_breakdowns,
        'most_recommended': most_recommended,
        'year_percentages': year_percentages,
        'decade_breakdown': decade_breakdown,
        'headline': headline
    }
    return render(request, 'shows/statistics.html', {'statistics': statistics})


def search(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ShowSearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            query = form.cleaned_data['search_query']
            payload = {
                'api_key': movie_api_key, 'query': query}
            response = requests.get(
                'https://api.themoviedb.org/3/search/multi', params=payload)
            shows, people = tv_helper.parse_search(response.json(), query)
            context = {'shows': shows,
                       'query': payload['query'], 'people': people}
            return render(request, 'shows/search.html', context)

    # if a GET (or any other method) we'll create a blank form
    elif request.GET.get('query'):
        query = request.GET.get('query')
        payload = {
            'api_key': movie_api_key, 'query': query}
        response = requests.get(
            'https://api.themoviedb.org/3/search/multi', params=payload)
        shows, people = tv_helper.parse_search(response.json(), query)
        context = {'shows': shows, 'query': payload['query'], 'people': people}
        return render(request, 'shows/search.html', context)

    else:
        form = ShowSearchForm()

    return render(request, 'shows/search.html', {'form': ShowSearchForm})


def wishlist(request):
    # pylint: disable=no-member
    context = {'shows': Show.objects.filter(wishlisted=True)}
    return render(request, 'shows/wishlist.html', context)


def wishlist_show(request, show_id):
    show = tv_helper.get_show_for_create(show_id)
    cast, crew = tv_helper.get_cast_and_crew(id)
    tv_helper.save_show(show, crew, cast, True)
    return HttpResponseRedirect(reverse('shows:view', args=(show['movie_db_id'],)))


def popular(request):
    shows = tv_helper.get_popular()
    return render(request, 'shows/popular.html', {'shows': shows})

shows/templates/shows/add.html
{% include './main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col"><h2>Add Show</h2></div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <form action="{% url 'shows:add' id %}" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Submit" />
      </form>
    </div>
    <div class="col"></div>
  </div>
</div>

shows/templates/shows/episode.html
{% include 'shows/main.html' %}

<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>{{ episode.name }} - {{show.name}} {{season.name}}</h2>
      {% if not watched and not wishlisted %}
      <button
        type="button"
        class="btn btn-info"
        style="margin-bottom: 10px; margin-top: 10px"
      >
        <a href="{% url 'shows:wishlist-show' show.id %}" style="color: white"
          >Wishlist</a
        >
      </button>
      {% endif %}
    </div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card text-center">
        <div class="card-header">Air Date</div>
        <div class="card-body">
          <h5 class="card-title">{{ episode.air_date }}</h5>
        </div>
      </div>
    </div>
    {% for member in episode.crew %}
    <div class="col">
      <div class="card text-center">
        <div class="card-header">{{member.job}}</div>
        <div class="card-body">
          <h5 class="card-title">
            <a href="{% url 'people:view' member.id %}">{{ member.name }}</a>
          </h5>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="row">
    <div class="card body-card shadow">
      <div id="text">
        <div class="row">
          <div class="col">
            <h5>Overview</h5>
            <p>{{ episode.overview }}</p>
            <hr />
            {% if episode.guest_stars %}
            <h5>Guest Stars</h5>
            <table class="table table-striped" style="width: 100%">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Actor</th>
                  <th scope="col">Role</th>
                </tr>
              </thead>
              <tbody>
                {% for star in episode.guest_stars %}
                <tr>
                  <td>
                    <a href="/people/{{star.id}}/view">{{ star.name }}</a>
                  </td>
                  {% if star.character %}
                  <td>{{star.character}}</td>
                  {% else %}
                  <td>N/A</td>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <!---->
            {% endif %}
          </div>
          {% if episode.still_path %}
          <div class="col">
            <div class="col text-center">
              <br />
              <img
                src="https://image.tmdb.org/t/p/original{{episode.still_path}}"
                style="width: 500px; height: 550px"
                alt="poster"
              />
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

shows/templates/shows/main.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap"
      rel="stylesheet"
    />
    <link rel="icon" href="<%= BASE_URL %>favicon.ico" />
    <script
      src="https://kit.fontawesome.com/d107bd8c1c.js"
      crossorigin="anonymous"
    ></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'global.css' %}" />

    <title>ShowTracker</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark background-tv">
      <a class="navbar-brand" href="/shows">
        <i class="fas fa-tv"> </i>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shows:popular' %}">Popular</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shows:wishlist-index' %}"
              >Wishlist</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shows:search' %}">Search</a>
          </li>
        </ul>
      </div>
      <form
        class="form-inline my-2 my-lg-0"
        method="GET"
        action="{% url 'shows:search' %}"
      >
        <input
          class="form-control mr-sm-2"
          type="search"
          name="query"
          id="query"
          placeholder="Search"
          aria-label="Search"
        />
        <button type="submit" class="btn btn-tv">Search</button>
      </form>
    </nav>
    <!-- {% block content %} {% endblock %} -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

shows/templates/shows/popular.html
{% include './main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>Popular Shows</h2>
      <br />
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <table class="table table-striped" style="margin: 50px 50px">
      <thead class="thead-info">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Genres</th>
          <th scope="col">Average Score</th>
          <th scope="col">Original Air Date</th>
          <th scope="col">Watched Status</th>
        </tr>
      </thead>
      <tbody>
        {% for row in shows %}
        <tr>
          <td>
            <a href="{% url 'shows:view' row.id %}">{{ row.name }}</a>
          </td>
          <td>{{ row.genres }}</td>
          <td>{{ row.vote_average }}</td>
          <td>{{ row.first_air_date }}</td>
          <td style="display: inline-block">
            <form
              class="form-inline"
              method="GET"
              style="float: left; padding-right: 5px"
              action="{% url 'shows:add' row.id %}"
            >
              <button
                type="submit"
                class="btn btn-success"
                method="GET"
                action="{% url 'shows:add' row.id %}"
              >
                Add
              </button>
            </form>

            <button type="button" class="btn btn-info">
              <a
                href="{% url 'shows:wishlist-show' row.id %}"
                style="color: white"
                >Wishlist</a
              >
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row"></div>
</div>

shows/templates/shows/search.html
{% include 'shows/main.html' %}
<div class="container-fluid">
  {% if not shows %}
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <h2>Search Show</h2>
    </div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <form method="POST">
        {% csrf_token %} {{ form }}
        <button type="submit" class="btn btn-info">Search</button>
      </form>
    </div>
    <div class="col"></div>
  </div>
  {% endif %} {% if shows %}
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <h2>Search Results for "{{ query }}":</h2>
    </div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Popularity</th>
            <th scope="col">Average Score</th>
            <th scope="col">First Air Date</th>
            <th scope="col">Watched Status</th>
          </tr>
        </thead>
        <tbody>
          {% for row in shows %}
          <!---->

          {% if row %}
          <tr>
            <td>
              <a href="{% url 'shows:view' row.id %}">{{ row.name }}</a>
            </td>
            <td>{{ row.popularity }}</td>
            <td>{{ row.vote_average }}</td>
            <td>{{ row.first_air_date }}</td>
            <td style="display: inline-block">
              <form
                class="form-inline"
                method="GET"
                style="float: left; padding-right: 5px"
                action="{% url 'shows:add' row.id %}"
              >
                <button
                  type="submit"
                  class="btn btn-success"
                  method="GET"
                  action="{% url 'shows:add' row.id %}"
                >
                  Add
                </button>
              </form>

              <button type="button" class="btn btn-info">
                <a
                  href="{% url 'shows:wishlist-show' row.id %}"
                  style="color: white"
                  >Wishlist</a
                >
              </button>
            </td>
          </tr>
          {% endif %}
          <!---->
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}
  <!---->
  {% if people %}
  <div class="row">
    <div class="col">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Popularity</th>
            <th scope="col">Known For</th>
          </tr>
        </thead>
        <tbody>
          {% for row in people %}
          <!---->

          {% if row %}
          <tr>
            <td>
              <a href="{% url 'people:view' row.id %}">{{ row.name }}</a>
            </td>
            <td>{{ row.popularity }}</td>
            <td>
              <a href="{% url 'view' row.known_for.id %}"
                >{{ row.known_for.title }}</a
              >
            </td>
          </tr>
          {% endif %}
          <!---->

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}
</div>

shows/templates/shows/season.html
{% include 'shows/main.html' %}

<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>{{ show.name }} - {{ season.name}}</h2>
      {% if not watched and not wishlisted %}
      <button
        type="button"
        class="btn btn-info"
        style="margin-bottom: 10px; margin-top: 10px"
      >
        <a href="{% url 'shows:wishlist-show' show.id %}" style="color: white"
          >Wishlist</a
        >
      </button>
      {% endif %}
      <!--  -->
      {% if not watched %}
      <button
        type="button"
        class="btn btn-success"
        style="margin-bottom: 10px; margin-top: 10px"
      >
        <a href="{% url 'shows:wishlist-show' show.id %}" style="color: white"
          >Already Watched</a
        >
      </button>
      {% endif %}
    </div>
    <div class="col"></div>
  </div>

  <div class="card body-card shadow">
    <div id="text">
      <div class="row">
        <div class="col">
          {% if season.overview %}
          <h5>Overview</h5>
          <p>{{ season.overview }}</p>
          <hr />
          {% endif %}
          <h5>Episodes</h5>
          <table class="table table-striped" style="width: 100%">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Overview</th>
                <th scope="col">Air Date</th>
                <th scope="col">Average Score</th>
              </tr>
            </thead>
            <tbody>
              {% for row in season.episodes %}
              <tr>
                <td>
                  <a
                    href="{% url 'shows:episode' show.id season.season_number row.episode_number %}"
                    >{{ row.name }}</a
                  >
                </td>
                <td>{{ row.overview }}</td>
                <td>{{ row.air_date }}</td>
                <td>{{ row.vote_average }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- {% if season.poster_path %}
        <div class="col">
          <div class="col text-center">
            <br />
            <img
              src="https://image.tmdb.org/t/p/original{{season.poster_path}}"
              style="width: 500px; height: 550px"
              alt="poster"
            />
          </div>
        </div>
        {% endif %} -->
      </div>
    </div>
  </div>
</div>

shows/templates/shows/show.html
{% include 'shows/main.html' %}

<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>{{ show.name }}</h2>
      {% if not watched and not wishlisted %}
      <button
        type="button"
        class="btn btn-info"
        style="margin-bottom: 10px; margin-top: 10px"
      >
        <a href="{% url 'shows:wishlist-show' show.id %}" style="color: white"
          >Wishlist</a
        >
      </button>
      {% endif %}
    </div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card text-center">
        <div class="card-header">Genre(s)</div>
        <div class="card-body">
          <h5 class="card-title">{{ show.genres }}</h5>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card text-center">
        <div class="card-header">Number of Seasons</div>
        <div class="card-body">
          <h5 class="card-title">{{ show.number_of_seasons }}</h5>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card text-center">
        <div class="card-header">First Aired</div>
        <div class="card-body">
          <h5 class="card-title">{{ show.first_air_date }}</h5>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card body-card shadow">
      <div id="text">
        <div class="row">
          <div class="col">
            <h5>Where To Watch (GB)</h5>
            {% if where.watch %}
            <h6>
              Free to subscribers: {% for option in where.watch %}
              <!--  -->
              {% for key, value in option.items %}
              <span>
                <img src="{{value}}" style="width: 50px; height: 50px" />
              </span>
              {% endfor %}
              <!---->
              {% endfor %}
              <!---->
            </h6>
            {% endif %}
            <!---->
            {% if where.buy %}
            <h6>
              Buy: {% for option in where.buy %}
              <!--  -->
              {% for key, value in option.items %}
              <span>
                <img src="{{value}}" style="width: 50px; height: 50px" />
              </span>
              {% endfor %}
              <!---->
              {% endfor %}
              <!---->
            </h6>
            {% endif %}
            <hr />
            <h5>Overview</h5>
            <p>{{ show.overview }}</p>
            <hr />

            <h5>Recommendations</h5>
            {% for item in show.recommendations %}
            <a href="{% url 'shows:view' item.id %}">{{ item.name }}</a> |
            <!---->
            {% endfor %}
            <hr />

            <h5>Cast</h5>
            <div>
              {% for person in cast %}
              <a href="{% url 'people:view' person.id %}">{{ person.name }}</a>
              |
              <!---->
              {% endfor %}
              <!---->
            </div>
            <hr />
            <h5>Seasons</h5>
            <div>
              {% for season in show.seasons %}
              <a href="{% url 'shows:season' show.id season.season_number %}"
                >{{ season.name }}</a
              >
              |
              <!---->
              {% endfor %}
              <!---->
            </div>
            <hr />
          </div>
          {% if poster %}
          <div class="col text-center">
            <br />
            <img
              src="{{poster}}"
              style="width: 500px; height: 550px"
              alt="poster"
            />
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>