auth/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('obtain_token', views.obtain_token, name='obtain-token'),
    path('refresh_token', views.refresh_token, name='refresh-token'),
    path('logout', views.logout, name='logout'),

]

filmtracker/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
from django.contrib.auth.views import LoginView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from django.contrib.auth import authenticate, login

urlpatterns = [
    path('', include('homepage.urls')),
    path('films/', include(('films.urls', 'films'), namespace='films')),
    path('people/', include(('people.urls', 'people'), namespace='people')),
    path('shows/', include(('shows.urls', 'shows'), namespace='shows')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include(('auth.urls', 'auth'), namespace='auth')),

]

people/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:id>/view', views.get_person, name='view'),
    path('<int:id>/like', views.like_person, name='like'),
    path('liked', views.liked_people, name='liked'),
    path('search', views.search, name='search'),

]

people/models.py
from django.db import models
# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=200)
    known_for = models.CharField(max_length=200, null=True)
    movie_db_id = models.IntegerField(null=True)

    def __str__(self):
        return self.name

people/views.py
from django.shortcuts import render
from . import people_helper
import json
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Person
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os
import requests
from operator import itemgetter
from django.db.models import Avg, Max, Q, Count, FloatField, F


movie_api_key = os.getenv("MOVIE_DB_KEY")


def get_person(request, id):
    person = people_helper.get_person(id)
    movie_credits, tv_credits = people_helper.get_credits(
        id, person['known_for_department'])
    # thanks to https://stackoverflow.com/questions/72899/how-do-i-sort-a-list-of-dictionaries-by-a-value-of-the-dictionary
    movie_credits = sorted(
        movie_credits, key=itemgetter('vote_average'), reverse=True)
    tv_credits = sorted(
        tv_credits, key=itemgetter('vote_average'), reverse=True)
    # movie_paginator = Paginator(movie_credits, 10)
    # tv_paginator = Paginator(tv_credits, 10)
    # page = request.GET.get('page')
    # is_movie = request.GET.get('movie')
    # try:
    #     if is_movie == 'True':
    #         movie_credits = movie_paginator.page(page)
    #         tv_credits = tv_paginator.page(1)
    #     elif is_movie == 'False':
    #         tv_credits = tv_paginator.page(page)
    #         movie_credits = movie_paginator.page(1)
    # except PageNotAnInteger:
    #     # If page is not an integer deliver the first page
    #     movie_credits = movie_paginator.page(1)
    #     tv_credits = tv_paginator.page(1)
    # except EmptyPage:
    #     # If page is out of range deliver last page of results
    #     if is_movie == 'True':
    #         movie_credits = movie_paginator.page(movie_paginator.num_pages)
    #     elif is_movie == 'False':
    #         tv_credits = tv_paginator.page(tv_paginator.num_pages)
    # if not page:
    #     movie_credits = movie_paginator.page(1)
    #     tv_credits = tv_paginator.page(1)

    return JsonResponse(data={'person': person, 'movie_credits': movie_credits, 'tv_credits': tv_credits})
    # return render(request, f'people/person.html', {'person': person, 'movie_credits': movie_credits, 'tv_credits': tv_credits, 'page': page})


def like_person(request, id):
    person = people_helper.get_person_for_create(id)
    liked_person = Person(
        name=person['name'], known_for=person['known_for'], movie_db_id=person['movie_db_id'])
    liked_person.save()
    return HttpResponseRedirect('/people/liked')


def liked_people(request):
    # pylint: disable=no-member
    people = Person.objects.all()
    people_paginator = Paginator(people, 10)
    page = request.GET.get('page')
    try:
        people = people_paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        people = people_paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        people = people_paginator.page(people_paginator.num_pages)
    if not page:
        people = people_paginator.page(1)
    return render(request, 'people/liked.html', {'people': people, 'page': page})


def search(request):
    # if this is a POST request we need to process the form data
    # if request.method == 'POST':
    #     # create a form instance and populate it with data from the request:
    #     form = FilmSearchForm(request.POST)
    #     # check whether it's valid:
    #     if form.is_valid():
    #         # process the data in form.cleaned_data as required
    #         # ...
    #         # redirect to a new URL:
    #         query = form.cleaned_data['search_query']
    #         payload = {
    #             'api_key': 'e6b24f5371e6fd462a8a26499fd466b2', 'query': query}
    #         response = requests.get(
    #             'https://api.themoviedb.org/3/search/multi', params=payload)
    #         films, people = film_helper.parse_search(response.json(), query)
    #         context = {'films': films,
    #                    'query': payload['query'], 'people': people}
    #         return render(request, 'films/search.html', context)

    # if a GET (or any other method) we'll create a blank form
    if request.GET.get('query'):
        query = request.GET.get('query')
        payload = {
            'api_key': movie_api_key, 'query': query}
        response = requests.get(
            'https://api.themoviedb.org/3/search/person', params=payload)
        people = people_helper.parse_search(response.json(), query)

        page = request.GET.get('page')
        people_paginator = Paginator(people, 10)
        try:
            people = people_paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer deliver the first page
            people = people_paginator.page(1)
        except EmptyPage:
            # If page is out of range deliver last page of results
            people = people_paginator.page(people_paginator.num_pages)
        if not page:
            people = people_paginator.page(1)
        return render(request, 'people/search.html', {'people': people, 'page': page, 'query': query})

    # elif not request.GET.get('page'):
    #     form = FilmSearchForm()

    # return render(request, 'people/search.html', {'form': FilmSearchForm})

people/templates/people/liked.html
{% include './main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>My Liked People</h2>
      <br />
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <table class="table table-striped" style="margin: 50px 50px">
      <thead class="thead-info">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Known For</th>
        </tr>
      </thead>
      <tbody>
        {% for row in people %}
        <tr>
          <td>
            <a href="{% url 'people:view' row.movie_db_id %}">{{ row.name }}</a>
          </td>
          <td>{{ row.known_for }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div style="margin-left: 50px">
      {% block content %}
      <!---->
      {% include "./pagination.html" with page=people %}
      <!---->
      {% endblock %}
    </div>
  </div>
  <div class="row"></div>
</div>

people/templates/people/main.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap"
      rel="stylesheet"
    />
    <link rel="icon" href="<%= BASE_URL %>favicon.ico" />
    <script
      src="https://kit.fontawesome.com/d107bd8c1c.js"
      crossorigin="anonymous"
    ></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'global.css' %}" />

    <title>FilmTracker</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark people">
      <a class="navbar-brand" href="/people">
        <i class="fas fa-user"></i>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/people/liked">Liked</a>
          </li>
        </ul>
      </div>
      <form
        class="form-inline my-2 my-lg-0"
        method="GET"
        action="/people/search"
      >
        <input
          class="form-control mr-sm-2"
          type="search"
          name="query"
          id="query"
          placeholder="Search"
          aria-label="Search"
        />
        <button type="submit" class="btn btn-custom">Search</button>
      </form>
    </nav>
    <!-- {% block content %} {% endblock %} -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

people/templates/people/pagination.html
<div class="pagination">
  {% if page.paginator.num_pages %}

  <!---->
  <!---->
  <nav aria-label="...">
    <ul class="pagination">
      {% if page.has_previous %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ page.previous_page_number }}&movie={{ movie }}"
          >Previous</a
        >
        {% endif %}
      </li>
      {% for n in page.paginator.page_range %}
      <li class="page-item {% if n == page.number %} active {% endif %}">
        <a class="page-link" href="?page={{ n }}&movie={{ movie }}">{{n}}</a>
      </li>
      {% endfor %}
      <!--  -->
      {% if page.has_next %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ page.next_page_number }}&movie={{ movie }}"
          >Next</a
        >
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>

people/templates/people/person.html
{% include './main.html' %}

<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>{{ person.name }}</h2>
      <br />
      <button
        type="button"
        class="btn btn-success"
        style="margin-bottom: 10px; margin-top: 10px"
      >
        <a href="{% url 'people:like' person.id %}" style="color: white"
          >Like</a
        >
      </button>
    </div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="card body-card shadow">
      <div id="text">
        <div class="row">
          <div class="col">
            <h5>Known for</h5>
            {{ person.known_for_department}}
            <hr />
            {% if person.place_of_birth %}
            <h5>Place of Birth</h5>
            <p>{{person.place_of_birth}}</p>
            <hr />
            {% endif %} {% if person.biography %}
            <h5>Biography</h5>
            <p>{{person.biography}}</p>
            <hr />
            {% endif %}
            <!---->
          </div>
          {% if person.image %}
          <div class="col">
            <div class="col text-center">
              <br />
              <img
                src="{{person.image}}"
                style="width: 500px; height: 550px"
                alt="poster"
              />
            </div>
          </div>
          {% endif %}
        </div>
        <div class="row">
          <div class="col">
            <h5>Movie Credits</h5>
            <table class="table table-striped" style="width: 100%">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Title</th>
                  <th scope="col">Role</th>
                  <th scope="col">Average Score</th>
                  <th scope="col">Release Date</th>
                </tr>
              </thead>
              <tbody>
                {% for row in movie_credits %}
                <tr>
                  <td>
                    <a href="{{row.movie_url}}">{{ row.title }}</a>
                  </td>
                  <td>{{ row.job }}</td>
                  <td>{{ row.vote_average }}</td>
                  <td>{{ row.release_date }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% block content %}
            <!---->
            {% include "./pagination.html" with page=movie_credits movie=True %}
            <!---->
            {% endblock %}
          </div>
          {% if tv_credits %}
          <div class="col">
            <h5>TV Credits</h5>
            <table class="table table-striped" style="width: 100%">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Role</th>
                  <th scope="col">No. of Episodes</th>
                  <th scope="col">Avg. Score</th>
                  <th scope="col">Original Air Date</th>
                </tr>
              </thead>
              <tbody>
                {% for row in tv_credits %}
                <tr>
                  <td>
                    <a href="{% url 'shows:view' row.show_id %}"
                      >{{ row.name }}</a
                    >
                  </td>
                  <td>{{ row.job }}</td>
                  <td>{{ row.episode_count }}</td>
                  <td>{{ row.vote_average }}</td>
                  <td>{{ row.release_date }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% block tvcontent %}
            <!---->
            {% include "./pagination.html" with page=tv_credits movie=False %}
            <!---->
            {% endblock %}
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

people/templates/people/search.html
{% include './main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <h2>Search Results for "{{ query }}":</h2>
    </div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col">
      {% if people %}
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Popularity</th>
            <th scope="col">Known For</th>
          </tr>
        </thead>
        <tbody>
          {% for row in people %}
          <!---->
          {% if row %}
          <tr>
            <td>
              <a href="{% url 'people:view' row.id %}">{{ row.name }}</a>
            </td>
            <td>{{ row.popularity }}</td>
            <td>
              <a href="{% url 'films:view' row.known_for.id %}"
                >{{ row.known_for.title }}</a
              >
            </td>
          </tr>
          {% endif %}
          <!---->

          {% endfor %}
        </tbody>
      </table>
      {% endif %}
      <!----->
      {% block content %}
      <!---->
      {% include "./pagination.html" with page=people %}
      <!---->
      {% endblock %}
    </div>
  </div>
</div>