auth/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('obtain_token', views.obtain_token, name='obtain-token'),
    path('refresh_token', views.refresh_token, name='refresh-token'),
    path('logout', views.logout, name='logout'),

]

films/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('popular', views.popular, name='popular'),
    path('upcoming', views.upcoming, name='upcoming'),
    path('festivals', views.festivals, name='festivals'),
    path('statistics', views.statistics, name='statistics'),
    path('top', views.top, name='top'),
    path('<int:movie_id>/add', views.add_movie, name='add'),
    path('<int:movie_id>/wishlist',
         views.wishlist_movie, name='wishlist-film'),
    path('wishlist', views.wishlist, name='wishlist-index'),
    path('<int:id>/like', views.like, name='like'),
    path('<int:id>/dislike', views.dislike, name='dislike'),
    path('<int:id>/view', views.get_film, name='view'),
    path('chart', views.years_chart, name='years-chart'),
    path('runtime-chart', views.runtime_chart, name='runtime-chart'),
    path('decades-chart', views.decades_chart, name='decades-chart'),
    path('ratings-chart', views.ratings_chart, name='ratings-chart'),
    path('genres', views.genres, name='genres'),
    path('discover', views.discover, name='discover'),


]

filmtracker/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
from django.contrib.auth.views import LoginView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from django.contrib.auth import authenticate, login

urlpatterns = [
    path('', include('homepage.urls')),
    path('films/', include(('films.urls', 'films'), namespace='films')),
    path('people/', include(('people.urls', 'people'), namespace='people')),
    path('shows/', include(('shows.urls', 'shows'), namespace='shows')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include(('auth.urls', 'auth'), namespace='auth')),

]

films/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.


class Film(models.Model):
    user = models.ForeignKey(User, verbose_name='User',
                             related_name='films', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=200)
    original_language = models.CharField(max_length=200)
    overview = models.TextField(null=True)
    movie_db_id = models.IntegerField(null=True)
    release_date = models.DateField(null=True)
    comments = models.CharField(max_length=200, null=True)
    popularity = models.TextField(null=True)
    runtime = models.IntegerField(null=True)
    budget = models.IntegerField(null=True)
    revenue = models.IntegerField(null=True)
    vote_average = models.FloatField(null=True)
    liked = models.BooleanField(null=True)
    added = models.BooleanField(null=True)
    wishlisted = models.BooleanField(null=True)
    score = models.FloatField(null=True)
    review = models.TextField(null=True)
    review_url = models.CharField(max_length=300, null=True)
    critics_pick = models.BooleanField(null=True)
    poster = models.CharField(max_length=200, null=True)
    date_watched = models.DateTimeField('Date Added', null=True)

    def __str__(self):
        return self.title


class ActingCredit(models.Model):
    user = models.ForeignKey(User, verbose_name='User',
                             related_name='actors', on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=200)
    role = models.CharField(max_length=200, null=True)
    movie_db_id = models.IntegerField()
    credit_id = models.CharField(max_length=200, null=True)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    def __str__(self):
        return '%s as %s in %s' % (self.name, self.role, self.film)


class Genre(models.Model):
    user = models.ForeignKey(User, verbose_name='User',
                             related_name='genres', on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Recommendation(models.Model):
    user = models.ForeignKey(User, verbose_name='User',
                             related_name='recommendations', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Keyword(models.Model):
    user = models.ForeignKey(User, verbose_name='User',
                             related_name='keywords', on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CrewCredit(models.Model):
    user = models.ForeignKey(User, verbose_name='User',
                             related_name='credits', on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=200)
    job = models.CharField(max_length=200)
    movie_db_id = models.IntegerField()
    credit_id = models.CharField(max_length=200, null=True)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    def __str__(self):
        return '%s as %s in %s' % (self.name, self.job, self.film)


class Token(models.Model):
    user = models.ForeignKey(User, verbose_name='User',
                             related_name='token', on_delete=models.CASCADE, default=1)
    value = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    expiry = models.DateTimeField()
    valid = models.BooleanField(default=True)

    def __str__(self):
        return str(self.value)

films/forms.py
from django import forms
from django.forms import ModelForm
from .models import Film


class FilmSearchForm(forms.Form):
    search_query = forms.CharField(label='Film Title', max_length=100)


class FilmForm(ModelForm):
    class Meta:
        model = Film
        fields = ['score', 'comments', 'date_watched']
        # Thanks to https://stackoverflow.com/questions/49440853/django-2-0-modelform-datefield-not-displaying-as-a-widget
        widgets = {
            'date_watched': forms.DateInput(format=('%m/%d/%Y'), attrs={'class': 'form-control', 'placeholder': 'Select a date', 'type': 'date'}),
        }

films/views.py
from django.shortcuts import render, redirect
import requests
from . import film_helper
import json
from datetime import date
import timeit
import functools
import collections
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from imdb import IMDb
from django.db.models.functions import ExtractYear
from .models import Film, Genre, Keyword, CrewCredit, ActingCredit, Token
from .forms import FilmSearchForm, FilmForm
from django.views.decorators.csrf import csrf_exempt

from . import stats
import time
from django.db.models.functions import Trunc
from plotly.offline import plot
from plotly.graph_objs import Scatter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Avg, Max, Q, Count, FloatField, F, DateField
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from datetime import datetime as dt
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# create an instance of the IMDb class

# https://api.themoviedb.org/3/search/movie
import os


movie_api_key = os.getenv("MOVIE_DB_KEY")


def years_chart(request, *filters):
    f = request.GET
    filters = {}
    current_user = request.user
    # print(current_user)
    # print(current_user.id)
    for key, value in f.items():
        if key == 'genre__in':
            value = value.split("&")
            value = [eval(x) for x in value]
            filters[key] = value
        if value == 'True':
            filters[key] = eval(value)
        else:
            filters[key] = value
    wishlist = True if f.get('wishlisted') == 'True' else False
    if 'genre__in' in filters.keys():
        # pylint: disable=no-member
        film_ids = Genre.objects.filter(
            movie_db_id__in=filters['genre__in']).values('film')
        del filters['genre__in']
        filters['pk__in'] = film_ids

    if current_user:
        filters['user'] = current_user

    labels = []
    data = {
        'one': [],
        'two': []
    }

    # pylint: disable=no-member
    films = Film.objects.filter(**filters).annotate(
        year=ExtractYear('release_date')).values('year').annotate(count=Count('year')).annotate(avg_score=Avg('score')) if filters else Film.objects.all().annotate(
        year=ExtractYear('release_date')).values('year').annotate(count=Count('year'))
    for entry in films:
        labels.append(entry['year'])
        data.get('one').append(entry['count'])
        if filters:
            data.get('two').append(entry['avg_score'])
    max_count = max(data.get('one'))
    return JsonResponse(data={
        'labels': labels,
        'data': data,
        'max': max_count
    })


def decades_chart(request, *filters):
    f = request.GET
    filters = {}
    current_user = request.user
    # print(current_user)
    # print(current_user.id)
    for key, value in f.items():
        if key == 'genre__in':
            value = value.split("&")
            value = [eval(x) for x in value]
            filters[key] = value
        if value == 'True':
            filters[key] = eval(value)
        else:
            filters[key] = value
    wishlist = True if f.get('wishlisted') == 'True' else False

    if 'genre__in' in filters.keys():
        # pylint: disable=no-member
        film_ids = Genre.objects.filter(
            movie_db_id__in=filters['genre__in']).values('film')
        del filters['genre__in']
        filters['pk__in'] = film_ids

    if current_user:
        filters['user'] = current_user

    labels = []
    data = {
        'one': [],
        'two': []
    }

    # pylint: disable=no-member
    films = Film.objects.filter(**filters).annotate(
        year=ExtractYear('release_date')) if filters else Film.objects.all().annotate(
        year=ExtractYear('release_date'))

    breakdown = {
        '1930s': (films.filter(year__gte=1930, year__lte=1939).count(), (films.filter(year__gte=1930, year__lte=1939).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '1940s': (films.filter(year__gte=1940, year__lte=1949).count(), (films.filter(year__gte=1940, year__lte=1949).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '1950s': (films.filter(year__gte=1950, year__lte=1959).count(), (films.filter(year__gte=1950, year__lte=1959).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '1960s': (films.filter(year__gte=1960, year__lte=1969).count(), (films.filter(year__gte=1960, year__lte=1969).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '1970s': (films.filter(year__gte=1970, year__lte=1979).count(), (films.filter(year__gte=1970, year__lte=1979).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '1980s': (films.filter(year__gte=1980, year__lte=1989).count(), (films.filter(year__gte=1980, year__lte=1989).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '1990s': (films.filter(year__gte=1990, year__lte=1999).count(), (films.filter(year__gte=1990, year__lte=1999).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '2000s': (films.filter(year__gte=2000, year__lte=2009).count(), (films.filter(year__gte=2000, year__lte=2009).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
        '2010s': (films.filter(year__gte=2010, year__lte=2019).count(), (films.filter(year__gte=2010, year__lte=2019).values_list(
            'score').aggregate(Avg('score'))['score__avg'])),
    }

    for key, value in breakdown.items():
        labels.append(key)
        data['one'].append(value[0])
        data['two'].append(value[1])
    max_count = max(data.get('one'))

    return JsonResponse(data={
        'labels': labels,
        'data': data,
        'max': max_count
    })


def runtime_chart(request, *filters):
    f = request.GET
    filters = {}
    current_user = request.user
    # print(current_user)
    # print(current_user.id)
    for key, value in f.items():
        if key == 'genre__in':
            value = value.split("&")
            value = [eval(x) for x in value]
            filters[key] = value
        if value == 'True':
            filters[key] = eval(value)
        else:
            filters[key] = value
    wishlist = True if f.get('wishlisted') == 'True' else False

    if 'genre__in' in filters.keys():
        # pylint: disable=no-member
        film_ids = Genre.objects.filter(
            movie_db_id__in=filters['genre__in']).values('film')
        del filters['genre__in']
        filters['pk__in'] = film_ids

    if current_user:
        filters['user'] = current_user

    labels = []
    data = {
        'one': [],
        'two': []
    }
    # pylint: disable=no-member
    films = Film.objects.filter(**filters).values('runtime').annotate(count=Count('runtime')).annotate(avg_score=Avg(
        'score')) if filters else Film.objects.all().values('runtime').annotate(count=Count('runtime')).annotate(avg_score=Avg('score'))
    for entry in films:
        labels.append(entry['runtime'])
        data['one'].append(entry['count'])
        data['two'].append(entry['avg_score'])
    max_count = max(data.get('one'))

    return JsonResponse(data={
        'labels': labels,
        'data': data,
        'max': max_count
    })


def ratings_chart(request, *filters):
    f = request.GET
    filters = {}
    current_user = request.user
    # print(current_user)
    # print(current_user.id)
    for key, value in f.items():
        if key == 'genre__in':
            value = value.split("&")
            value = [eval(x) for x in value]
            filters[key] = value
        if value == 'True':
            filters[key] = eval(value)
        else:
            filters[key] = value
    wishlist = True if f.get('wishlisted') == 'True' else False

    if 'genre__in' in filters.keys():
        # pylint: disable=no-member
        film_ids = Genre.objects.filter(
            movie_db_id__in=filters['genre__in']).values('film')
        del filters['genre__in']
        filters['pk__in'] = film_ids

    if current_user:
        filters['user'] = current_user

    labels = []
    data = {
        'one': [],
        'two': []
    }
    # pylint: disable=no-member
    # pylint: disable=no-member
    films = Film.objects.filter(**filters).values('vote_average').annotate(count=Count('vote_average')) if filters else Film.objects.all(
    ).values('vote_average').annotate(count=Count('vote_average'))

    films_my_score = Film.objects.filter(**filters).values('score').annotate(count_score=Count('score')) if filters else Film.objects.all(
    ).values('score').annotate(count_score=Count('score'))

    d = {}
    for entry in films:
        d[entry['vote_average']] = (entry['count'], 0)
    for entry in films_my_score:
        if d.get(entry['score']) is not None:
            old = d[entry['score']]
            d[entry['score']] = (old[0], entry['count_score'])
        else:
            d[entry['score']] = (0, entry['count_score'])
    d = {k: v for k, v in d.items() if k is not None}
    d = collections.OrderedDict(sorted(d.items()))
    for key, value in d.items():
        labels.append(key)
        data['one'].append(value[0])
        data['two'].append(value[1])

    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })


def index(request):
    # print(request.user)
    # # permission_classes = (IsAuthenticated,)
    # # authentication_class = JSONWebTokenAuthentication
    # print(request.user.is_authenticated)

    # film_helper.bulk_create_films(request)

    # pylint: disable=no-member
    if not request.user:

films/templates/films/add.html
{% include 'films/main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col"><h2>Add Movie</h2></div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <form action="{% url 'films:add' id %}" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Submit" />
      </form>
    </div>
    <div class="col"></div>
  </div>
</div>

films/templates/films/festivals.html
{% include 'films/main.html' %}

<div class="container-fluid">
  <div class="row">
    <div class="col">
      <br />
    </div>
  </div>
  <div class="card shadow">
    <div id="text">
      <div class="row">
        <div class="col">
          <div class="card text-center">
            <div class="card-header">Cannes</div>
            <div class="card-body">
              <h5 class="card-title">
                {% load static %}
                <!-- https://www.cleanpng.com/png-2-15-cannes-film-festival-logo-2-14-cannes-film-fe-6269453/ -->
                <img src="{% static 'cannes.png' %}" alt="Cannes" />
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

films/templates/films/index.html
{% include 'films/main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>My Films</h2>
      <br />
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <button
        type="button"
        class="btn btn-success"
        style="margin-bottom: 10px; margin-top: 10px"
      >
        <a href="{% url 'films:statistics' %}?added=True" style="color: white"
          >Statistics</a
        >
      </button>
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <table class="table table-striped" style="margin: 50px 50px">
      <thead class="thead-info">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Genres</th>
          <th scope="col">Average Score</th>
          <th scope="col">My Score</th>
          <th scope="col">Date Watched</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for row in films %}
        <tr>
          <td>
            <a href="{% url 'films:view' row.movie_db_id %}">{{ row.title }}</a>
          </td>
          <td>{{ row.genres }}</td>
          <td>{{ row.vote_average }}</td>
          <td>{{ row.score }}</td>
          <td>{{ row.date_watched|date:"SHORT_DATE_FORMAT" }}</td>
          <td style="display: inline-block">
            {% if not row.liked and row.liked is not False %}
            <button type="button" class="btn btn-success">
              <a
                href="{% url 'films:like' row.movie_db_id %}"
                style="color: white"
                >Like</a
              >
            </button>
            <button type="button" class="btn btn-danger">
              <a
                href="{% url 'films:dislike' row.movie_db_id %}"
                style="color: white"
                >Dislike</a
              >
            </button>
            {% endif %}
            <!---->
            {% if row.liked %}
            <span style="color: #3eaf7c">Liked</span>
            {% endif %}
            <!--  -->
            {% if row.liked is False %}
            <span style="color: red">Disliked</span>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div style="margin-left: 50px">
      {% block content %}
      <!---->
      {% include "./pagination.html" with page=films %}
      <!---->
      {% endblock %}
    </div>
  </div>
  <div class="row"></div>
</div>

films/templates/films/main.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap"
      rel="stylesheet"
    />
    <link rel="icon" href="<%= BASE_URL %>favicon.ico" />
    <script
      src="https://kit.fontawesome.com/d107bd8c1c.js"
      crossorigin="anonymous"
    ></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'global.css' %}" />

    <title>FilmTracker</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
      <a class="navbar-brand" href="/films">
        <i class="fas fa-film"></i>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'films:top' %}">Top</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'films:popular' %}">Popular</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'films:upcoming' %}">Upcoming</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'films:wishlist-index' %}"
              >Wishlist</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'films:festivals' %}">Festivals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'films:search' %}">Search</a>
          </li>
        </ul>
      </div>
      <form
        class="form-inline my-2 my-lg-0"
        method="GET"
        action="/films/search"
      >
        <input
          class="form-control mr-sm-2"
          type="search"
          name="query"
          id="query"
          placeholder="Search"
          aria-label="Search"
        />
        <button type="submit" class="btn btn-custom">Search</button>
      </form>
    </nav>
    <!-- {% block content %} {% endblock %} -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

films/templates/films/popular.html
{% include './main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>Popular Films</h2>
      <br />
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <table class="table table-striped" style="margin: 50px 50px">
      <thead class="thead-info">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Genres</th>
          <th scope="col">Average Score</th>
          <th scope="col">Release Date</th>
          <th scope="col">Watched Status</th>
        </tr>
      </thead>
      <tbody>
        {% for row in films %}
        <tr>
          <td>
            <a href="{% url 'films:view' row.id %}">{{ row.title }}</a>
          </td>
          <td>{{ row.genres }}</td>
          <td>{{ row.vote_average }}</td>
          <td>{{ row.release_date }}</td>
          <td style="display: inline-block">
            <form
              class="form-inline"
              method="GET"
              style="float: left; padding-right: 5px"
              action="{% url 'films:add' row.id %}"
            >
              <button
                type="submit"
                class="btn btn-success"
                method="GET"
                action="{% url 'films:add' row.id %}"
              >
                Add
              </button>
            </form>

            <button type="button" class="btn btn-info">
              <a
                href="{% url 'films:wishlist-film' row.id %}"
                style="color: white"
                >Wishlist</a
              >
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row"></div>
</div>

films/templates/films/top.html
{% include './main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>Top Rated Films</h2>
      <br />
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <table class="table table-striped" style="margin: 50px 50px">
      <thead class="thead-info">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Genres</th>
          <th scope="col">Average Score</th>
          <th scope="col">Release Date</th>
          <th scope="col">Watched Status</th>
        </tr>
      </thead>
      <tbody>
        {% for row in films %}
        <tr>
          <td>
            <a href="{% url 'films:view' row.id %}">{{ row.title }}</a>
          </td>
          <td>{{ row.genres }}</td>
          <td>{{ row.vote_average }}</td>
          <td>{{ row.release_date }}</td>
          <td style="display: inline-block">
            <form
              class="form-inline"
              method="GET"
              style="float: left; padding-right: 5px"
              action="{% url 'films:add' row.id %}"
            >
              <button
                type="submit"
                class="btn btn-success"
                method="GET"
                action="{% url 'films:add' row.id %}"
              >
                Add
              </button>
            </form>

            <button type="button" class="btn btn-info">
              <a
                href="{% url 'films:wishlist-film' row.id %}"
                style="color: white"
                >Wishlist</a
              >
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row"></div>
</div>

films/templates/films/upcoming.html
{% include './main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>Upcoming Releases</h2>
      <br />
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <table class="table table-striped" style="margin: 50px 50px">
      <thead class="thead-info">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Genres</th>
          <th scope="col">Average Score</th>
          <th scope="col">Release Date</th>
          <th scope="col">Watched Status</th>
        </tr>
      </thead>
      <tbody>
        {% for row in films %}
        <tr>
          <td>
            <a href="{% url 'films:view' row.id %}">{{ row.title }}</a>
          </td>
          <td>{{ row.genres }}</td>
          <td>{{ row.vote_average }}</td>
          <td>{{ row.release_date }}</td>
          <td style="display: inline-block">
            <form
              class="form-inline"
              method="GET"
              style="float: left; padding-right: 5px"
              action="{% url 'films:add' row.id %}"
            >
              <button
                type="submit"
                class="btn btn-success"
                method="GET"
                action="{% url 'films:add' row.id %}"
              >
                Add
              </button>
            </form>

            <button type="button" class="btn btn-info">
              <a
                href="{% url 'films:wishlist-film' row.id %}"
                style="color: white"
                >Wishlist</a
              >
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row"></div>
</div>

films/templates/films/wishlist_index.html
{% include 'films/main.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <br />
      <h2>My Wishlisted Films</h2>
      <br />
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <div class="col"></div>
    <div class="col text-center">
      <button
        type="button"
        class="btn btn-success"
        style="margin-bottom: 10px; margin-top: 10px"
      >
        <a
          href="{% url 'films:statistics' %}?wishlisted=True"
          style="color: white"
          >Statistics</a
        >
      </button>
    </div>
    <div class="col"></div>
  </div>

  <div class="row">
    <table class="table table-striped" style="margin: 50px 50px">
      <thead class="thead-info">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Genres</th>
          <th scope="col">Average Score</th>
          <th scope="col">Date Wishlisted</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for row in films %}
        <tr>
          <td>
            <a href="{% url 'films:view' row.movie_db_id %}">{{ row.title }}</a>
          </td>
          <td>{{ row.genres }}</td>
          <td>{{ row.vote_average }}</td>
          <td>{{ row.date_watched|date:"SHORT_DATE_FORMAT" }}</td>
          <td>
            <form
              class="form-inline"
              method="GET"
              style="float: left; padding-right: 5px"
              action="{% url 'films:add' row.id %}"
            >
              <button
                type="submit"
                class="btn btn-success"
                method="GET"
                action="{% url 'films:add' row.id %}"
              >
                Add
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div style="margin-left: 50px">
      {% block content %}
      <!---->
      {% include "./pagination.html" with page=films %}
      <!---->
      {% endblock %}
    </div>
  </div>
  <div class="row"></div>
</div>